# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFileDialog, QMainWindow
import sys
import json
import settings



selectedFile = ""

indexes = ["Project ID", "Number Alt", "Project Name", "Building Name", "Building Address", "Building City", "Building State", "Building Zip", "Assigned To", "Type", "Subtype", "Status", "Status Date", "Who Created", "Date Created", "Modified", "Who Modified", "Bid Amount",  "Original Contract Amount", "Revised Contract Amount", "Outstanding Contract Amount", "Gross Profit Margin %", "Notes", "Actual Project Cost", "Actual Project Cost Who", "Actual Project Cost Date", "Source", "Budget Amount", "Budget Notes", "Budget Dates", "Contract With Object", "Contract With Name", "Contract With Office Name", "Salesperson Name", "Contract Terms", "Contract Term Notes", "Division", "Reference", "Subsource", "Client PO Number", "Local Union", "Construction Capacity", "Exclusions", "Special Instructions", "Contract Date", "Hide Daily Work Crew", "Running Notes", "Reference Notes", "Serial Number", "Production Status", "Contract Status", "Contract Status Date Open", "Contract Status Completed", "Contract Status Date Closed", "Contract Status Who Open", "Contract Status Who Completed", "Contract Status Who Closed", "Production Status Date", "Status Who", "Production Status Who", "Contact Name", "Contact Phone Number", "Contact Email"]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MVR Dataforma Converter")
        MainWindow.resize(607, 256)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(460, 50, 121, 131))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")

        self.selectButton = QtWidgets.QPushButton(self.splitter)
        self.selectButton.setToolTip("")
        self.selectButton.setObjectName("selectButton")

        self.convertButton = QtWidgets.QPushButton(self.splitter)
        self.convertButton.setToolTip("")
        self.convertButton.setObjectName("convertButton")

        self.settingsButton = QtWidgets.QPushButton(self.splitter)
        self.settingsButton.setToolTip("")
        self.settingsButton.setObjectName("settingsButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.selectButton.clicked.connect(lambda: self.clicked("Select"))
        self.convertButton.clicked.connect(lambda: self.clicked("Convert"))
        self.settingsButton.clicked.connect(lambda: self.clicked("Settings"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectButton.setStatusTip(_translate("MainWindow", "Browse and select desired CSV file"))
        self.selectButton.setText(_translate("MainWindow", "Select"))
        self.convertButton.setStatusTip(_translate("MainWindow", "Converts selected CSV file to formatted XLSX"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.settingsButton.setStatusTip(_translate("MainWindow", "Access your format settings "))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))

    def clicked(self, text):
        if(text == "Select"):
            selectedFile = QFileDialog.getOpenFileName(MainWindow, 'Open file', 'c:\\',"Comma Seperated Values (*.csv)")
            
    




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
