import json

settings = {
    "Project ID":True,
    "Number Alt":True,
    "Project Name":True,
    "Building Name":True,
    "Building Address":True,
    "Building City":True,
    "Building State":True,
    "Building Zip":True,
    "Assigned To":True,
    "Type":True,
    "Subtype":True,
    "Status":True,
    "Status Date":True,
    "Who Created":True,
    "Date Created":True,
    "Modified":True,
    "Who Modified":True,
    "Bid Amount":True,
    "Original Contract Amount":True,
    "Revised Contract Amount":True,
    "Outstanding Contract Amount":True,
    "Gross Profit Margin %":True,
    "Notes":True,
    "Actual Project Cost":True,
    "Actual Project Cost Who":True,
    "Actual Project Cost Date":True,
    "Source":True,
    "Budget Amount":True,
    "Budget Notes":True,
    "Budget Dates":True,
    "Contract With Object":True,
    "Contract With Name":True,
    "Contract With Office Name":True,
    "Salesperson Name":True,
    "Contract Terms":True,
    "Contract Term Notes":True,
    "Division":True,
    "Reference":True,
    "Subsource":True,
    "Client PO Number":True,
    "Local Union":True,
    "Construction Capacity":True,
    "Exclusions":True,
    "Special Instructions":True,
    "Contract Date":True,
    "Hide Daily Work Crew":True,
    "Running Notes":True,
    "Reference Notes":True,
    "Serial Number":True,
    "Production Status":True,
    "Contract Status":True,
    "Contract Status Date Open":True,
    "Contract Status Date Completed":True,
    "Contract Status Date Closed":True,
    "Contract Status Who Open":True,
    "Contract Status Who Completed":True,
    "Contract Status Who Closed":True,
    "Production Status Date":True,
    "Status Who":True,
    "Production Status Who":True,
    "Contact Name":True,
    "Contact Phone Number":True,
    "Contact Email":True,
}

launchSettings = {
    "First Launch":True,
}
