# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsWindow(object):
    def setupUi(self, settingsWindow):
        settingsWindow.setObjectName("settingsWindow")
        settingsWindow.resize(278, 324)
        self.centralwidget = QtWidgets.QWidget(settingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sortBy = QtWidgets.QComboBox(self.centralwidget)
        self.sortBy.setGeometry(QtCore.QRect(20, 10, 231, 31))
        self.sortBy.setObjectName("sortBy")
        self.ascendDescend = QtWidgets.QComboBox(self.centralwidget)
        self.ascendDescend.setGeometry(QtCore.QRect(20, 50, 231, 31))
        self.ascendDescend.setObjectName("ascendDescend")
        self.itemsShown = QtWidgets.QListWidget(self.centralwidget)
        self.itemsShown.setGeometry(QtCore.QRect(10, 90, 256, 192))
        self.itemsShown.setObjectName("itemsShown")
        settingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 278, 21))
        self.menubar.setObjectName("menubar")
        settingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(settingsWindow)
        self.statusbar.setObjectName("statusbar")
        settingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(settingsWindow)
        QtCore.QMetaObject.connectSlotsByName(settingsWindow)

    def retranslateUi(self, settingsWindow):
        _translate = QtCore.QCoreApplication.translate
        settingsWindow.setWindowTitle(_translate("settingsWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsWindow = QtWidgets.QMainWindow()
    ui = Ui_settingsWindow()
    ui.setupUi(settingsWindow)
    settingsWindow.show()
    sys.exit(app.exec_())
